### ISSUE TITLE
Transform To Technology [P0f] returned with an error

### ISSUE THREAD

**Issue by Jeandelanou** [allfro/canari#56]
Hello,
I have a problems with the execution of transforms. I have the following error (example with p0f):

Running transform To Technology [P0f] on 1 entities (from entity "***.***.***.***")
Transform To Technology [P0f] returned with an error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/canari-1.1-py2.7.egg/canari/maltego/utils.py", line 222, in local_transform_runner
    ) if get_transform_version(transform_module.dotransform) == 2 else transform_module.dotransform(
  File "/usr/local/lib/python2.7/dist-packages/sploitego-1.5-py2.7.egg/sploitego/transforms/p0f.py", line 31, in dotransform
    i = fingerprint(request.value)
  File "/usr/local/lib/python2.7/dist-packages/sploitego-1.5-py2.7.egg/sploitego/cmdtools/p0f.py", line 102, in fingerprint
    stdout=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory (from entity "***.***.***.***")

What is the solution?? I own Maltego Chlorie 

Thank you

**Comment by PhilDunphy** [comment]
@Jeandelanou I have hit the same issue. Have you solved this?

**Comment by ipatrol** [comment]
Same issue here. Make sure that the location of p0f in ~/.canari/sploitego.conf is correct. I think it used to be installed to /opt, but now it's installed more organically.

**Comment by PhilDunphy** [comment]
@ipatrol Thanks. No more errors!! No to return some results. Do you guys know of any test domains that Maltego can be pointed at other than creating my own vm lab?
